name: Update documentation

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-docs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js environment
        uses: ./.github/actions/node_env_setup
        with:
          node-version-file: .nvmrc
          pnpm-version: "10"
          install-dependencies: "true"

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: sudo apt-get update && sudo apt-get install -y zip

      - name: Publish on gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm run documentation-deploy-to-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
